### ISSUE TITLE
Error if no intensity image is provided

### ISSUE THREAD

**Issue by GenevieveBuckley** [haesleinhuepf/napari-simpleitk-image-processing#10]
The label statistics function produces an error if an intensity image is not provided. This happens even in cases where only statistics that do *not* require intensity are requested (eg: size, shape, position).

To reproduce:
1. Open napari and load some labels
```python
import napari
from skimage.data import binary_blobs
from skimage.measure import label

blobs = label(binary_blobs(length=64, volume_fraction=0.05, n_dim=3))
viewer = napari.view_labels(blobs)
```
2. Open "label statistics" from the napari-simpleitk-image-processing plugin menu: `Plugins` > `napari-simpleitk-image-processing` > `label statistics`
3. Uncheck the "intensity" checkbox (but leave the "size" checkbox selected).
4. Click the "Run" button on the plugin, and observe the error message

<details>
<summary>Full traceback (click to expand):</summary>

```python-traceback
  File "C:\Users\CryoEM\.conda\envs\napari-empanada\lib\site-packages\SimpleITK\extra.py", line 184, in _get_sitk_pixelid
    return _np_sitk[numpy_array_type.dtype]
KeyError: dtype('O')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CryoEM\.conda\envs\napari-empanada\lib\site-packages\magicgui\widgets\_bases\value_widget.py", line 57, in _on_value_change
    self.changed.emit(value)
  File "psygnal\\_signal.py", line 725, in psygnal._signal.SignalInstance.emit
  File "psygnal\\_signal.py", line 767, in psygnal._signal.SignalInstance._run_emit_loop
  File "psygnal\\_signal.py", line 768, in psygnal._signal.SignalInstance._run_emit_loop
  File "psygnal\\_signal.py", line 788, in psygnal._signal.SignalInstance._run_emit_loop
  File "C:\Users\CryoEM\.conda\envs\napari-empanada\lib\site-packages\magicgui\widgets\_function_gui.py", line 207, in _disable_button_and_call
    self.__call__()
  File "C:\Users\CryoEM\.conda\envs\napari-empanada\lib\site-packages\magicgui\widgets\_function_gui.py", line 318, in __call__
    value = self._function(*bound.args, **bound.kwargs)
  File "C:\Users\CryoEM\.conda\envs\napari-empanada\lib\site-packages\napari_simpleitk_image_processing\_simpleitk_image_processing.py", line 814, in label_statistics
    sitk_intensity_image = sitk.GetImageFromArray(intensity_image)
  File "C:\Users\CryoEM\.conda\envs\napari-empanada\lib\site-packages\SimpleITK\extra.py", line 292, in GetImageFromArray
    id = _get_sitk_pixelid(z)
  File "C:\Users\CryoEM\.conda\envs\napari-empanada\lib\site-packages\SimpleITK\extra.py", line 189, in _get_sitk_pixelid
    raise TypeError('dtype: {0} is not supported.'.format(numpy_array_type.dtype))
TypeError: dtype: object is not supported.

If you suspect this is an IPython 8.4.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

</details>

Additional details:
* Operating system: Windows 10
* python version: 3.9
* napari version: 0.4.15
* napari-simpleitk-image-processing version: 0.4.0

**Comment by GenevieveBuckley** [comment]
From the stack trace, the problem is likely around line 814 of `napari_simpleitk_image_processing\_simpleitk_image_processing.py`

https://github.com/haesleinhuepf/napari-simpleitk-image-processing/blob/09352aaceb66e49eef3ed25388f886836ad79410/src/napari_simpleitk_image_processing/_simpleitk_image_processing.py#L814

It's probably worth adding a check to see if any image data was provided, before attempting to pass it to `sitk.GetImageFromArray`

**Comment by haesleinhuepf** [comment]
Hi @GenevieveBuckley ,

thanks for reporting this! I'd phrase it a feature-request, and a reasonable one. It should now work with [version 0.4.1](https://github.com/haesleinhuepf/napari-simpleitk-image-processing/releases/tag/0.4.1). Please try it out:

```
pip install napari-simpleitk-image-processing==0.4.1
```

It will also be available via conda, likely tomorrow.

Let me know if it works then in your use-case!

Thanks again!

Best,
Robert

**Comment by GenevieveBuckley** [comment]
Thanks, I'll give it a go!
